name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: ['8.0']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0
      - name: install
        run: |
          yarn install
      - name: lint
        run: |
          yarn run lint
      - name: test
        run: |
          yarn run test:cov
        env:
          DBTEST: mongodb://localhost/nestjs-mongo?replicaSet=rs0
      - name: build
        run: |
          yarn run build
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true
